
import type { Metadata } from 'next';
import './globals.css';
import { Lexend } from 'next/font/google';
import dynamic from 'next/dynamic';
import { ReduxProvider } from '@/redux/provider';
import { getCookieString } from '@/lib/cookie';

// Import AuthChecker (sử dụng dynamic để không ảnh hưởng đến SSR)
const AuthChecker = dynamic(() => import('@/components/auth/AuthChecker'), {
  ssr: true,
});

export const metadata: Metadata = {
  title: 'F8',
  description: 'Generated by create next app',
  icons: 'https://fullstack.edu.vn/favicon/favicon_32x32.png',
};
const lexend = Lexend({
  subsets: ['latin', 'vietnamese'],
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  display: 'swap',
});
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieString = await getCookieString();
  return (
    <html lang="en">
      <body className={lexend.className}>
        <ReduxProvider>
          <AuthChecker cookieString={cookieString}>
            <main>
              {children}
            </main>
          </AuthChecker>
        </ReduxProvider>
      </body>
    </html>
  );
}
