import type { Metadata } from 'next';
import './globals.css';
import { Lexend } from 'next/font/google';
import { cookies } from 'next/headers';
import dynamic from 'next/dynamic';
import { ReduxProvider } from '@/redux/provider';


export const metadata: Metadata = {
  title: 'F8',
  description: 'Generated by create next app',
  icons: 'https://fullstack.edu.vn/favicon/favicon_32x32.png',
};
const lexend = Lexend({
  subsets: ['latin', 'vietnamese'],
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  display: 'swap',
});
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();

  return (
    <html lang="en">
      <body className={lexend.className}>
        <ReduxProvider>
          <main>
            {children}
          </main>
        </ReduxProvider>
      </body>
    </html>
  );
}
